# Generated by Django 5.0.14 on 2026-05-28 11:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(blank=True, max_length=100, null=True)),
                ('main_class', models.CharField(blank=True, max_length=100, null=True)),
                ('commence_date', models.DateField(blank=True, null=True)),
                ('sum_insured', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('fund_type', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_nic', models.CharField(blank=True, max_length=20, null=True)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('link_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('sum_insured', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('foreign_sum_insured', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('foreign_premium_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('annual_premium_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('foreign_annual_premium_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('commence_date', models.DateField(blank=True, null=True)),
                ('link_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=100)),
                ('is_payable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('policy_type', models.CharField(choices=[('Individual Health', 'Individual Health'), ('Family Floater', 'Family Floater'), ('Corporate', 'Corporate'), ('Senior Citizen', 'Senior Citizen')], default='Individual Health', max_length=50)),
                ('holder_name', models.CharField(max_length=255)),
                ('holder_nic', models.CharField(blank=True, max_length=12, null=True)),
                ('opd_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('branch', 'Branch Manager'), ('customer', 'Customer')], default='customer', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('nic', models.CharField(blank=True, max_length=12, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('claim_type', models.CharField(choices=[('opd', 'OPD (Out Patient)'), ('dental', 'Dental'), ('spectacle', 'Spectacles')], default='opd', max_length=50)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('validation_score', models.IntegerField(default=0)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='Unknown', max_length=20)),
                ('treatment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='claim_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.claim')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('Self', 'Self'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent')], default='Self', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_name', models.CharField(choices=[('BOC', 'Bank of Ceylon'), ('Peoples', "People's Bank"), ('Commercial', 'Commercial Bank'), ('HNB', 'Hatton National Bank'), ('Sampath', 'Sampath Bank'), ('Seylan', 'Seylan Bank'), ('NDB', 'National Development Bank'), ('NTB', 'Nations Trust Bank'), ('DFCC', 'DFCC Bank'), ('Pan Asia', 'Pan Asia Bank'), ('Union', 'Union Bank'), ('NSB', 'National Savings Bank')], default='BOC', max_length=100)),
                ('account_number', models.CharField(max_length=15)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.policy')),
            ],
        ),
    ]
