# Generated by Django 5.0.14 on 2026-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_claim_diagnosis_claim_doctor_name_claim_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='rag_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
