# Generated by Django 5.0.14 on 2026-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_claim_rag_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinsurance',
            name='holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
