# Generated by Django 5.0.14 on 2026-05-31 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_holder_name_to_groupinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRuleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('holder_name', models.CharField(blank=True, max_length=255)),
                ('policy_type', models.CharField(choices=[('Individual Health', 'Individual Health'), ('Family Floater', 'Family Floater'), ('Corporate', 'Corporate'), ('Senior Citizen', 'Senior Citizen'), ('Unknown', 'Unknown')], default='Corporate', max_length=50)),
                ('cover_start', models.DateField(blank=True, null=True)),
                ('cover_end', models.DateField(blank=True, null=True)),
                ('original_pdf', models.FileField(upload_to='policy_pdfs/')),
                ('extracted_rules', models.JSONField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extraction_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
