# Generated by Django 5.0.14 on 2026-06-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_add_submission_count_to_claim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinemaster",
            name="generic_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
